import { StartupIdea, PitchSlide } from '@/types/pitch';

export function generateDemoPitchDeck(idea: StartupIdea): PitchSlide[] {
  const slides: PitchSlide[] = [
    {
      id: 'slide-1',
      type: 'title',
      title: `${idea.startupName}`,
      content: `${idea.startupName}
      
Revolutionizing ${idea.industry} with innovative solutions

• Solving real problems for ${idea.targetAudience}
• Powered by cutting-edge technology
• Ready to scale and make an impact

Generated by PitchPal - AI Startup Pitch Generator`,
      order: 1,
    },
    {
      id: 'slide-2',
      type: 'problem',
      title: 'The Problem',
      content: `${idea.problemStatement}

Key Pain Points:
• Current solutions are inadequate or expensive
• ${idea.targetAudience} struggle with existing options
• Market gap represents significant opportunity
• Time-sensitive need for better solutions

Market Impact:
• Affects millions of potential users
• Represents billions in market opportunity
• Growing demand for innovative solutions`,
      order: 2,
    },
    {
      id: 'slide-3',
      type: 'solution',
      title: 'Our Solution',
      content: `${idea.solution}

Key Benefits:
• Addresses core pain points directly
• User-friendly and intuitive design
• Scalable technology platform
• Proven results and customer satisfaction

Unique Value Proposition:
• 10x better than existing solutions
• Reduces costs by 50%
• Saves users 5+ hours per week
• Seamless integration with existing workflows`,
      order: 3,
    },
    {
      id: 'slide-4',
      type: 'market',
      title: 'Market Opportunity',
      content: `${idea.marketSize || 'Large and growing market opportunity'}

Market Size:
• Total Addressable Market (TAM): $10B+
• Serviceable Addressable Market (SAM): $2B
• Serviceable Obtainable Market (SOM): $200M

Market Trends:
• 25% annual growth rate
• Increasing digital adoption
• Rising demand for automation
• Shift towards sustainable solutions

Target Segments:
• Primary: ${idea.targetAudience}
• Secondary: Adjacent market segments
• Enterprise and SMB opportunities`,
      order: 4,
    },
    {
      id: 'slide-5',
      type: 'business-model',
      title: 'Business Model',
      content: `${idea.monetizationPlan}

Revenue Streams:
• Subscription-based recurring revenue
• Premium feature upgrades
• Enterprise licensing deals
• Professional services and support

Pricing Strategy:
• Freemium model to drive adoption
• Competitive pricing vs. alternatives
• Value-based pricing for enterprise
• Multiple tiers to capture different segments

Unit Economics:
• Customer Acquisition Cost (CAC): $50
• Lifetime Value (LTV): $500
• LTV/CAC Ratio: 10:1
• Gross Margin: 85%`,
      order: 5,
    },
    {
      id: 'slide-6',
      type: 'go-to-market',
      title: 'Go-to-Market Strategy',
      content: `Customer Acquisition Strategy:

Digital Marketing:
• Content marketing and SEO
• Social media advertising
• Influencer partnerships
• Webinars and thought leadership

Sales Strategy:
• Inside sales for SMB segment
• Direct sales for enterprise
• Partner channel development
• Customer referral program

Launch Plan:
• Beta testing with key customers
• Product Hunt and tech media launch
• Industry conference presentations
• Strategic partnership announcements

Traction Metrics:
• 1,000+ beta users signed up
• 95% customer satisfaction score
• 40% month-over-month growth
• $50K ARR in first 6 months`,
      order: 6,
    },
    {
      id: 'slide-7',
      type: 'competitive-advantage',
      title: 'Competitive Advantage',
      content: `${idea.competitors}

Our Competitive Moat:

Technology Advantages:
• Proprietary AI algorithms
• Patent-pending innovations
• Superior performance metrics
• Scalable cloud architecture

Market Position:
• First-mover advantage in niche
• Strong brand recognition
• Network effects and viral growth
• High switching costs

Team & Execution:
• World-class engineering team
• Deep industry expertise
• Proven track record of success
• Strong investor backing

Barriers to Entry:
• Significant R&D investment required
• Complex regulatory requirements
• Established customer relationships
• Data network effects`,
      order: 7,
    },
    {
      id: 'slide-8',
      type: 'team',
      title: 'Our Team',
      content: `${idea.teamOverview || 'Experienced team with proven track record'}

Leadership Team:
• CEO: Former VP at Fortune 500 company
• CTO: Ex-Google engineer with 15+ years experience
• VP Sales: Built $100M+ revenue at previous startup
• VP Marketing: Growth expert from unicorn company

Advisory Board:
• Industry veterans and thought leaders
• Successful entrepreneurs and investors
• Technical experts and domain specialists
• Strategic partners and customers

Team Highlights:
• Combined 50+ years of industry experience
• Previously built and sold companies
• Deep technical and business expertise
• Passionate about solving this problem

We're Hiring:
• Expanding engineering team
• Building world-class sales organization
• Looking for top talent to join our mission`,
      order: 8,
    },
    {
      id: 'slide-9',
      type: 'financials',
      title: 'Financial Projections',
      content: `5-Year Financial Forecast:

Revenue Growth:
• Year 1: $100K ARR
• Year 2: $500K ARR
• Year 3: $2M ARR
• Year 4: $8M ARR
• Year 5: $25M ARR

Key Metrics:
• Customer Growth: 10x annually
• Revenue per Customer: $500/year
• Gross Margin: 85%
• Customer Churn: <5% annually

Funding Requirements:
• Seed Round: $500K (completed)
• Series A: $3M (current round)
• Series B: $15M (planned Year 3)

Use of Funds:
• 60% Product development
• 25% Sales & Marketing
• 10% Operations
• 5% Working capital

Path to Profitability:
• Break-even by Year 3
• 25% EBITDA margin by Year 5
• Strong cash generation for growth`,
      order: 9,
    },
    {
      id: 'slide-10',
      type: 'ask',
      title: 'The Ask',
      content: `Investment Opportunity:

Funding Request: $3M Series A

Use of Funds:
• $1.8M (60%) - Product Development
  - Expand engineering team
  - Build advanced features
  - Enhance platform scalability

• $750K (25%) - Sales & Marketing
  - Customer acquisition campaigns
  - Sales team expansion
  - Marketing automation tools

• $300K (10%) - Operations
  - Legal and compliance
  - Finance and accounting
  - Office and infrastructure

• $150K (5%) - Working Capital
  - General corporate purposes
  - Strategic reserves

Expected Milestones:
• 10,000+ active users by Year 2
• $2M ARR by Year 3
• Series B funding round
• Market leadership position

ROI Potential:
• 10x return potential for investors
• Clear path to $100M+ valuation
• Strong exit opportunities
• Proven market demand`,
      order: 10,
    },
  ];

  return slides;
}

export function generateDemoExecutiveSummary(idea: StartupIdea): string {
  return `EXECUTIVE SUMMARY

Company: ${idea.startupName}
Industry: ${idea.industry}
Founded: 2024

COMPANY OVERVIEW
${idea.startupName} is a ${idea.industry} company that ${idea.solution.toLowerCase()}. We are addressing the critical problem of ${idea.problemStatement.toLowerCase()}, which affects ${idea.targetAudience}.

PROBLEM & SOLUTION
The market currently suffers from inadequate solutions that are expensive, inefficient, and difficult to use. Our innovative platform solves this by providing a comprehensive, user-friendly solution that delivers 10x better results at 50% lower cost.

MARKET OPPORTUNITY
We are targeting a $10B+ total addressable market with strong growth fundamentals. The market is experiencing 25% annual growth driven by digital transformation and increasing demand for automation.

BUSINESS MODEL
${idea.monetizationPlan} Our freemium model drives user acquisition while premium tiers capture value from power users and enterprises. We project $25M ARR by Year 5 with 85% gross margins.

COMPETITIVE ADVANTAGE
${idea.competitors} Our proprietary technology, first-mover advantage, and world-class team create strong competitive moats that will be difficult for competitors to replicate.

TEAM
${idea.teamOverview || 'Our experienced leadership team combines deep industry expertise with proven execution capabilities. We have successfully built and scaled companies before.'}

FINANCIAL PROJECTIONS
• Year 1: $100K ARR
• Year 3: $2M ARR  
• Year 5: $25M ARR
• Break-even by Year 3
• 25% EBITDA margin by Year 5

FUNDING REQUEST
We are raising $3M Series A to accelerate product development, expand our team, and scale customer acquisition. This funding will enable us to capture market leadership and achieve our ambitious growth targets.

INVESTMENT HIGHLIGHTS
• Huge market opportunity ($10B+ TAM)
• Proven product-market fit
• Strong unit economics and scalability
• Experienced team with track record
• Clear path to profitability
• 10x+ return potential for investors

Generated by PitchPal - AI Startup Pitch Generator`;
}

export const isDemoMode = (): boolean => {
  const apiKey = process.env.OPENAI_API_KEY;
  // Check if API key is missing, placeholder, or if we should force demo mode
  return !apiKey ||
         apiKey.includes('your_') ||
         apiKey === 'your_openai_api_key' ||
         apiKey.length < 10 ||
         process.env.FORCE_DEMO_MODE === 'true';
};
